spring.application.name=authservice
server.port=8081

# ============================================
# DB Connection
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5433/fracturescope_db
spring.datasource.username=postgres
spring.datasource.password=Luci2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ============================================
# JWT Configuration
# ============================================
jwt.secret=myVerySecretKeyForJWTTokenGenerationThatShouldBeLongEnough123456
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.model=llama-3.3-70b-versatile